# fly.toml app configuration file generated for forms-cert-ninja on 2026-06-03T20:24:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'forms-cert-ninja'
primary_region = 'gru'

[env]
INACTIVE_TIMEOUT="15m"
FRONTEND_URL="https://forms.cert.ninja"
OAUTH_GOOGLE_KEY="594508944460-4k73o5mql0o16sudsidlbuuejm878n0l.apps.googleusercontent.com"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'

[mounts]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

